version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "actions/checkout"
        version: "v4"
  # Maintain dependencies for dockerfiles
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
