name: Run lint and static analyis checks
on:
  workflow_call:
    inputs:
      tardigradelint-target:
        description: Name of the Tardigrade-CI Makefile target to run
        default: lint
        required: false
        type: string

jobs:
  tardigradelint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Project Syntax Verification
        run: make docker/run target=${{ inputs.tardigradelint-target }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Check workflow files
        uses: reviewdog/action-actionlint@c6ee1eb0a5d47b2af53a203652b5dac0b6c4016e
