name: Run test jobs
on:
  workflow_call:
    inputs:
      mockstacktest-enable:
        description: Controls whether to run the mockstacktest job
        default: true
        required: false
        type: boolean
      mockstacktest-pytest-args:
        description: Passes PYTEST_ARGS to mockstacktest
        default: -v
        required: false
        type: string

jobs:
  mockstacktest:
    if: inputs.mockstacktest-enable
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Start the mock AWS stack
        run: make mockstack/up

      - name: Apply Terraform test configs in mock AWS stack
        run: make mockstack/pytest PYTEST_ARGS="${{ inputs.mockstacktest-pytest-args }}"

      - name: Cleanup the mock AWS stack
        run: make mockstack/clean
